### ISSUE TITLE
Hotfix - Adicionar correções ao Roadmap

### ISSUE THREAD

**Issue by clarissalimab** [fga-eps-mds/2018.2-Kalkuli#110]
## Descrição da Issue
Corrige alguns erros encontrados no documento, além de incluir textos faltantes.

### Tasks:
- [x] Incluir Sprint 6 (Sprint da Release)
- [x] Colocar as datas de cada Sprint

**Comment by MarianaPicolo** [comment]
Uma sugestão: colocar as datas das _sprints_ ao lado do seu número
