### ISSUE TITLE
Evoluir US10 - Editar Envio de Uma Nota

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#119]
Ajustar a história com as modificações a seguir:    

- [x] Guardar os dados extraídos do PDF no Redux
- [x] Ao realizar o upload de uma nota fiscal, o usuário deve receber um feedback de que a nota foi carregada para que ele saiba que já pode seguir para a próxima tela.
- [x] Colocar labels nos inputs dos campos das notas para que o usuário saiba do que se tratam.
- [x] Colocar labels nos campos das notas na visão detalhada de uma nota.
- [x] Colocar labels nos campos das notas na lista de notas.
- [x] Corrigir rota da edição de notas para que ela não mude a partir da rota de upload de notas/ visualização detalhada da nota, não sendo acessível por outro meio que não seguindo o fluxo de editar.
- [x] Corrigir rota da confirmação para que ela não mude a partir da rota de upload de notas/ visualização detalhada da nota, não sendo acessível por outro meio que não seguindo o fluxo de editar.

**Comment by clarissalimab** [comment]
Coloquei os critérios, meninos! Se alguma coisa não estiver clara, comentem aqui que eu explico melhor 😘

**Comment by MarianaPicolo** [comment]
![photo_2018-09-30_18-49-25](https://user-images.githubusercontent.com/26073710/46263169-0b894a80-c4e2-11e8-831f-44218cbbf6cf.jpg)  

- Ajustar o espaço entre os botões e o lado direto do modal
