### ISSUE TITLE
Evoluir Identidade Visual

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#121]

**Comment by clarissalimab** [comment]
Gente, será que vocês podem arrumar uma coisinha? Eu pensei em colocar a identidade em uma página separada do protótipo, e na nova página do protótipo colocar algumas telas principais além do link pra acessar o protótipo inteiro, tipo assim: https://github.com/fga-eps-mds/2017.1-Forum-Coordenadores-DEG/wiki/Prot%C3%B3tipos-de-Alta-Fidelidade

O que vocês acham?

**Comment by MarianaPicolo** [comment]
> Gente, será que vocês podem arrumar uma coisinha? Eu pensei em colocar a identidade em uma página separada do protótipo, e na nova página do protótipo colocar algumas telas principais além do link pra acessar o protótipo inteiro, tipo assim: https://github.com/fga-eps-mds/2017.1-Forum-Coordenadores-DEG/wiki/Prot%C3%B3tipos-de-Alta-Fidelidade
> 
> O que vocês acham?

Teríamos que abrir um hotfix, mas eu gosto da ideia.

**Comment by clarissalimab** [comment]
@MarianaPicolo Pra mim acho que não precisa abrir um hotfix, já que eles estão arrumando a identidade visual eles podem ajustar isso, ou eu posso colocar isso na issue de arrumar a wiki, mas acho que aqui é mais simples.

**Comment by MarianaPicolo** [comment]
@clarissalimab Essa issue já foi finalizada.
Mas essa modificação pode ser adicionada à issue de 'Ajustar wiki'

**Comment by clarissalimab** [comment]
@MarianaPicolo Certo, vou colocar lá então 😜

**Comment by clarissalimab** [comment]
Corrigir escrita no tópico "Comunicação entre os serviços" do documento de arquitetura para "a qual será responsável..."

![image](https://user-images.githubusercontent.com/15739610/46308378-d9362680-c58f-11e8-9ac8-5639891f9d0c.png)
