### ISSUE TITLE
US33 - Gerar Relatório por Período Definido

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#126]
## US33     

Eu, como **usuário do sistema**, desejo que um **relatório gerado contemple apenas o período que eu definir** para que eu possa ter uma **lista de todos os gastos apenas nas datas escolhidas**.

***

### Critérios de Aceitação:   
- Ao escolher gerar um relatório, o usuário deve ter acesso a uma opção que permita que ele escolha um dia de início e um dia de fim para que o relatório gerado contemple as notas do período selecionado.
- Selecionadas as datas, o usuário clica em gerar relatório e um relatório é gerado contemplando as notas no período que o usuário escolheu.
- Se o usuário escolher um período que não possui nenhuma nota, o sistema deve retornar uma mensagem de erro dizendo que não existem notas cadastradas naquele período.
- O usuário não deve poder escolher uma data que ainda não aconteceu.

***   

#### Front-end
- [x] Implementar o date-picker
- [x] Tratar erro de data mal selecionada
- [x] Botão de salvar relatório
- [x] Exibir relatório para o usuário
- [x] Comunicação entre Front e Back 
- [x] Implementar o Date-picker nas telas Dashboard, Notas e Relatórios
#### Back-end
- [x] Receber data selecionada para realizar a filtragem (2018.2_Receipts)
- [x] Verificar se no período selecionado, existem notas
- [x] Realizar filtragem baseada no período 
- [x] Retornar dados para o front (GET)
- [x] Salvar relatório no banco de reports (POST)
- [x] Testes

**Comment by clarissalimab** [comment]
Coloquei os critérios, meninos! Se alguma coisa não estiver clara, comentem aqui que eu explico melhor 😘

**Comment by lucasdutraf** [comment]
@Phe0 , @devsalula e eu adicionamos as tasks! :+1:

**Comment by devsalula** [comment]
Biblioteca para o Datepicker:
https://reactdatepicker.com/

**Comment by Phe0** [comment]
Tasks refatoradas
