### ISSUE TITLE
US35 - Inserir Descrição e Título na Nota

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#151]
## US35     

Eu, como **usuário do sistema**, desejo que as **notas tenham descrição e título** para que eu possa **pesquisá-las posteriormente**.

***

### Critérios de Aceitação:   
-  No momento da submissão ou edição de uma nota, o usuário terá acesso a um campo de título e um campo de descrição onde ele poderá, opcionalmente, escrever o texto desejado.
- Depois de inseridos o título e a descrição, essas informações devem aparecer na lista de notas e na visualização detalhada de cada nota.

***   

#### Front-end
- [x] Adicionar os campos de título e descrição no componente da nota
- [x] Mapear os inputs necessário para cada campo da nota
- [x] Validação de obrigatoriedade nos campos
- [x] Criar um map no componente List para os dados das notinhas
- [x] Criar um map no componente ReceiptView para os dados da nota
#### Testes
- [x] ReceiptCompare
#### Back-end
- [x] Adicionar novos atributos na model 
- [x] Adicionar os novos atributos nos testes
- [x] Adicionar os novos atributos nos métodos existentes

**Comment by MarianaPicolo** [comment]
@clarissalimab 
 - Critérios de Aceitação

@youssef-md, @EsioFreitas e @lucasdutraf 
 - Tasks

**Comment by clarissalimab** [comment]
Coloquei os critérios, se tiverem alguma dúvida é só falar! Bom trabalho ❤️
