### ISSUE TITLE
US12 - Excluir Nota do Sistema

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#154]
## US12     

Eu, como **usuário do sistema**, desejo **excluir uma nota fiscal** para que eu possa **dispensar uma nota que não precisa existir no sistema**.

***

### Critérios de Aceitação:   
-  A partir da visualização detalhada de uma nota, o usuário poderá excluí-la.
- Ao clicar no botão para executar a ação, o sistema deve exibir uma confirmação da ação para que o usuário não exclua acidentalmente uma nota alertando que a ação não pode ser desfeita.
- Confirmada a ação, o sistema retorna para a lista de notas atualizada, sem a nota que já foi excluída do sistema.
***   

#### _Front-end_
- [x] Ação do botão excluir   
- [x] Component de confirmação para a exclusão da nota 
- [x] Fundo nas opções do MenuButton
- [x] Ligar o cancelar do ReceiptAdder
- [x] Redirecionar confirmar do ReceiptAdder para o /list-all-receipts
- [x] Comunicação front - Gateway 
- [x] Renderizar pagina sem a nota excluída
- [x] Guardar e recuperar as notas do Redux

Testes:
- [x] ConfirmationMessage 
- [x] Lists
- [x] ReceiptLists com Axios get 
- [x] ReceiptView com Axios delete
#### _Back-end_
- [x] Comunicação com o Gateway - Receipts 
- [x] Método DELETE 
- [x] Testes

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação

@lucasdutraf, @EsioFreitas e @youssef-md 
- _Tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios, se tiverem alguma dúvida é só falar! Bom trabalho ❤️

**Comment by EsioFreitas** [comment]
Tasks adicionadas!! <3
