### ISSUE TITLE
Feedback R1

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2018.2-Kalkuli#159]
- Falta controle de versões nos docs

- Tap ficou muito boa! (Entenderam as mudanças propostas)
- Matriz de avaliação de valor - melhor artefato!
- Documentação da Sprint está boa, porém não escalável (a análise do SM pode ser resumida, ou colocado um quadro de praticas ágeis que são analisada somente os pontos críticos e melhorias observadas) -- colocar em forma discursiva dificulta rastreabilidade.. 
- Falta documento de qualidade "(?)
- "É um conjunto de verdades para o correto funcionamento da aplicação” - documento de arquitetura
-  Quadro de conhecimento nao contempla ops
- Arquitetura - cade o roadmap do papel - tem evidencia de trabalho. 
- Devops - cadê o roadmap do papel (não está claro o que precisa ser feito, quais is riscos - 9 issues de devops) - #35 - nao tem rastreabilidade
- Bernardo e Pedro ausentes
- Sprint documentação overhead -  monitorar praticas
- Quanta duplicação 
- Produto - refinar a visão (mais madura) - integrar com sistema de contabilidade dela - empresas juniores, condomínios, pequenas empresas.
- Produto  - pessoal - falta muita coisa  (NAO ENTRAR NESSE MERCADO)
- Deixar claro as limitações da ferramenta- e pensar dentro do fluxo da leitura
- Caso de exceção (como regra) e tratar dentro do sistema

**Comment by clarissalimab** [comment]
Agradecemos o feedback, @RochaCarla!

**Comment by MarianaPicolo** [comment]
Adotaremos as sugestões!
