### ISSUE TITLE
US01 - Inserir o Cadastro de Uma Empresa no Sistema

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#163]
## US01      

Eu, como **administrador de empresa**, desejo **cadastrar minha empresa no sistema** para que eu possa ter **controle dos gastos** da minha empresa.     

***

### Critérios de Aceitação:   
-  A partir da tela inicial do sistema, o usuário poderá selecionar a opção de cadastrar uma empresa;
- Selecionada a opção, o usuário terá acesso a um formulário de cadastro da empresa;
- Dados obrigatórios da empresa:
     - Razão social da empresa
     - E-mail (esclarecer que este e-mail deve ser da empresa, ou seja, o e-mail cadastrado ficará vinculado à empresa)
- Dados opcionais da empresa:
     - Nome fantasia da empresa
     - Telefone
     - CNPJ
     - CEP
     - Cidade e estado
- No momento em que uma empresa é cadastrada, um usuário administrador também é cadastrado;
- Dados obrigatórios do usuário:
     - Nome
     - E-mail
     - Senha
- Feito o cadastro, os dados da empresa e do usuário responsável devem estar guardados no sistema;
- O sistema deve garantir que não seja possível realizar mais de um cadastro com o mesmo e-mail;
- O sistema deve prover feedbacks ao usuário conforme as ações são executadas.

Esta história **não contempla**:
- Cadastro individual de um usuário (exceto pelo descrito acima, que deve ser realizado no momento do cadastro de uma empresa);
- Login no sistema;
- Separar dados de notas fiscais dentro do conteúdo de cada empresa.

***   

#### _Front-end_
- [x]  Formulário de cadastro;
- [x]  Feedbacks ao usuário;
- [x]  Testes.

#### _Back-end_
- [x]  Criar Model da empresa;
- [x]  Criar Model do usuário;
- [x]  Receber e salvar dados no banco;
- [x] Conectar o Back com o Front
- [x] Criptografar senha
- [x] Verificar se já existe email no banco
- [x]  Testes.

**Comment by MarianaPicolo** [comment]
@clarissalimab 
 - Critérios de Aceitação

@EsioFreitas e @devsalula 
- _Tasks_

**Comment by clarissalimab** [comment]
Pessoal, coloquei os critérios da história de vocês. Essa história é um pouco complexa de entender, eu tentei ser o mais clara possível, mas se precisarem de ajuda com alguma coisa, podem perguntar. Eu posso ter esquecido de algum dado relevante nos dados da empresa ou do usuário, se vocês notarem alguma coisa, avisem também. Divirtam-se! :smile_cat:
