### ISSUE TITLE
US29 - Exportar Relatório em .csv

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#164]
## US29      

Eu, como **usuário do sistema**, desejo baixar um **relatório em formato de planilha** para que eu possa ter uma **versão exportada dos meus gastos**.

***

### Critérios de Aceitação:   
- Gerado um relatório, o usuário deve ter acesso a um botão de "Exportar";
- Ao clicar no botão, o sistema dispara uma conversão do formato do relatório para .CSV e baixa o arquivo exportado;
- Todas as informações do relatório devem estar devidamente organizadas;
- O sistema deve prover feedbacks ao usuário conforme as ações são executadas.

***   

#### _Front-end_
- [x]  Exibir o componente Botão Exportar na Página de Relatórios salvos;
- [x]  Exibir solicitar para o usuário aonde ele deseja salvar o arquivo .CSV;
- [x]  Exibir um Feedback para o usuário informando que o .CSV foi mandado para download;
- [ ] Testes

#### _Back-end_
- [x]  Estudar mais sobre a conversão de JSON em .CSV;
- [x] Receber JSON no back;
- [x] Converter JSON para CSV;
- [x] Conectar Back com o Front;
- [x] Testes

**Comment by MarianaPicolo** [comment]
@clarissalimab 
 - Critérios de Aceitação

@EsioFreitas e @devsalula 
- _Tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios de aceitação de vocês! Qualquer dúvida, só chamar. Divirtam-se! :smile_cat:
