### ISSUE TITLE
Melhorar Responsividade do Site

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#165]
## Melhorar Responsividade do Site
Para melhorar a usabilidade do site em diferentes tipos de dispositivos, precisamos que o site esteja mais responsivo.

### Critérios de aceitação
- Os componentes das páginas do site não podem perder em alinhamento e funcionalidade conforme o tamanho da tela mudar.

#### Somente css: 
- [x] Homepage
- [x] SignUp
- [x] ReceipAdder
- [x] Reports
- [x] Dashboard
- [x] ReceiptList / Receipt
- [x] MenuButton

#### React e css:
- [x] NavBar
- [x] DatePicker
- [x] HomeNavBar

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação

**Comment by clarissalimab** [comment]
Coloquei critérios de aceitação, mas não sei direito como posso medir a responsividade para definir critérios. Dei uma pesquisada, mas não encontrei nada. Sugiro que vocês identifiquem o que não está responsivo na ferramenta e coloquem cada coisa que precisam mudar como tasks para se organizarem melhor e para podermos ver o desenvolvimento da issue de vocês. Divirtam-se :smile_cat:

**Comment by youssef-md** [comment]
Eu e @Phe0 iremos fazer um levantamento de todos os componentes que não estão responsivos, e de como eles deverão se comportar para que fique mais agradável ao usuário, dependendo da quantidade de componentes e da complexidade das mudanças necessárias precisaremos alocar outra sprint para a finalizaçao dessa issue.

**Comment by MarianaPicolo** [comment]
@youssef-md e @Phe0, anotem os resultados desse levantamento e os coloquem como _tasks_.
