### ISSUE TITLE
Criar Guia de Teste de Usabilidade

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#169]
## Criar Guia de Teste de Usabilidade
Para obter feedbacks sobre a ferramenta, serão aplicados testes de usabilidade nas funcionalidades prontas a partir das próximas sprints. Assim, será possível começar a agir em cima das correções levantadas o mais cedo possível.

- [ ] Criar os cenários de testes de usabilidade para o estado atual da ferramenta;
- [ ] Criar o modelo de relatório dos resultados dos testes de usabilidade.

**Comment by MarianaPicolo** [comment]
@clarissalimab 
 - _Tasks_;

**Comment by clarissalimab** [comment]
Coloquei as tasks.
