### ISSUE TITLE
US18 - Inserir Categoria em Nota

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#174]
## US18     

Eu, como **usuário do sistema**, desejo que **categorias sejam adicionadas aos meus gastos** para que eu possa ter uma **classificação das minhas compras**.

***

### Critérios de Aceitação:   
- As notas agora devem ter um atributo para categoria.
- Cada nota deve ter apenas uma categoria.
- A categoria deve ser selecionada no momento em que o usuário está submetendo a nota: ele deverá ter acesso a um dropdown com categorias pré-definidas.
- Adicionada uma categoria à nota, a categoria deve aparecer na lista de notas e na visão detalhada de uma nota.

**Essa história não contempla:**
- Criar uma nova categoria, ou seja, nessa história só é necessário criar algumas categorias engessadas para que apenas a funcionalidade de associar uma nota a uma categoria esteja pronta.
- Filtrar notas por categoria.
- Gerar relatórios por categoria.

***   

#### _Back-end:_   
- [x] Entidade de Categoria
- [x] Relacionamento entre Categoria e Nota
- [x] Endpoint para recuperar todas as notas
- [x] Endpoint para atribuir uma categoria a uma nota
- [x] Endpoint no Gateway para pegar todas as tags
- [x] Endpoint no Gateway para mudar o valor do tag_id
- [x] Script para criar uma categorias desejadas
- [x] Teste do Endpoint para recuperar todas as categorias
- [x] Teste do Endpoint para atribuir categoria a nota
#### _Front-end_:   
- [x] Layout de adição de categoria
- [x] Componente para um único item
- [x] Componente de busca
- [x] Componente do Drop down
- [x] Requisição para popular o Drop down
- [x] Atualizar a store com a nova nota
- [x] Visualizar a Tag no componente ReceiptView
- [x] Visualizar a Tag no componente List
- [x] Mockar/Testar o request de recuperação Tags
- [x] Testar o componente TagItem
- [x] Testar o componente SavedTagItem
- [x] Testar o componente searchBar
- [x] Testar o componente DropDown

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação;

@youssef-md e @lucasdutraf 
- _Tasks_;

**Comment by clarissalimab** [comment]
Adicionei os critérios! Quando forem criar as categorias, criem umas 4 categorias prontas. Vocês podem se basear um pouco no jeito que é para adicionar labels a issues no GitHub. Divirtam-se! 😺 
![image](https://user-images.githubusercontent.com/15739610/47653936-850b6b80-db68-11e8-8dc9-3566486573b9.png)

**Comment by youssef-md** [comment]
Eu e @lucasdutraf adicionamos as taks inicias
