### ISSUE TITLE
US09 - Realizar Login

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#175]
## US09     

Eu, como **usuário do sistema**, desejo **realizar _login_ no sistema** para que eu tenha **acesso às suas funcionalidades**.

***

### Critérios de Aceitação:
- Cadastrado um usuário, ele poderá inserir suas credenciais para ter acesso ao sistema.   
- O sistema deve agora estar adaptado ao sistema de permissão, ou seja, o usuário só poderá ter acesso às funcionalidades se estiver logado.

**Essa história não contempla:**
- Funcionalidade de recuperar senha.
- Excluir uma conta.

***   

#### _Back-end:_   
- [x]  Endpoint no Gateway para realizar requisição com serviço de usuário
- [x] Query para a validação do usuário
- [x] Adicionar campos na model User
- [x] Criar métodos para criação do token
- [x] Endpoint para o login ser realizado
- [x] Endpoint para o logout ser realizado
- [x] Endpoint para o registro ser realizado
- [x] Criar SECRET_KEY
- [x] Aplicar Hash na senha antes de salvar senha no banco
- [x] Método para decodificar token
- [x] Método para codificar token
- [x] Estabelecer relação 1:1 no banco
- [x] testes para todas as exceções

#### _Front-end_:   
- [x] Componente para o Log in
- [x] Validação dos campos
- [x] Ver a senha digitada
- [x] Recuperação dos valores
- [x] Tratar usuário não registrado
- [x] Conexão para guardar o auth_token na Store do Redux
- [x] Persistencia do token no localStorage
- [x] Restrição ao acesso das rotas(Guards)
- [x] Testar HomeNavBar
- [x] Testar Login

**Comment by MarianaPicolo** [comment]
@clarissalimab 
- Critérios de aceitação;

@youssef-md e @lucasdutraf 
- _Tasks_;

**Comment by clarissalimab** [comment]
Coloquei os critérios. Se tiverem qualquer dúvida, só chamar. Divirtam-se! 😺

**Comment by youssef-md** [comment]
Eu e @lucasdutraf adicionamos as tasks iniciais, porém temos que amadurecer nosso conhecimento sobre log in e validação de usuário.
