### ISSUE TITLE
US15 - Filtrar Notas por Título e Descrição

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#194]
## US15     

Eu, como **usuário do sistema**, desejo **filtrar notas por título e descrição** para que eu possa **encontrar notas de acordo com o critério definido**.

***

### Critérios de Aceitação:
- O usuário, na tela de notas, poderá fazer uma procura através de uma barra de pesquisas
- Se o termo pesquisado for equivalente ao título, descrição ou cnpj de alguma nota, será mostrada uma lista com essas notas
- Se não houver nada escrito o sistema deverá mostrar todas as notas
- Se nenhuma nota possuir o termo procurado o sistema deverá mostrar um aviso dizendo que não existem notas com esses termos

**Essa história não contempla:**
- Filtrar notas pelo local de emissão
- Filtrar notas pelo valor dos impostos
- Filtrar notas pelo valor total
- Filtrar notas pela categoria
- Filtrar Relatórios 
- Gerar relatórios a partir do termo procurado

***   

#### _Front-end_:   
- [x] Criar barra de pesquisa
- [x] Fazer métodos de filtragen
- [x] Feedbacks para o usuário
- [x] Testes

**Comment by MarianaPicolo** [comment]
@clarissalimab e @Phe0 critérios de aceitação;

@Phe0 e @devsalula _tasks_

**Comment by Phe0** [comment]
na verdade eu tava pensando aqui q quase todas as procuras fazem sentido.
Posso querer saber do local, saber oq eu comprei nas lojas americanas por exemplo 
ou então o responsável do financeiro pode saber q houve um gasto de 250 reais por exemplo mas não sabe de q
mas não sei se aumenta demais a história
@clarissalimab

**Comment by Phe0** [comment]
a gente poderia fazer um dropdown com os tipos de filtragem por exemplo, onde ele tem q especificar se é cnpj, local, valor, etc

**Comment by clarissalimab** [comment]
@Phe0 Sim, mas acho que esse é outro tipp de filtro daí. Eu acho que talvez seja uma situação muito específica o usuário lembrar o valor que ele gastou mas não lembrar com o quê.

Acho que esse filtro por valor faz mais sentido se puder ser por intervalo, como nos sites de compra que você pode filtrar por valor, mas aparece em intervalos ou o usuário mesmo pode definir o intervalo que ele quer. Só que acho que isso fica para outra história mesmo, melhor fragmentar.

**Comment by Phe0** [comment]
@clarissalimab deixamos título, descrição e cnpj então?

**Comment by clarissalimab** [comment]
@Phe0 por mim, sim

**Comment by Phe0** [comment]
critérios de aceitação atualizados
