### ISSUE TITLE
US37 - Criar Categorias

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#195]
## US37     

Eu, como **usuário do sistema**, desejo **criar categorias** para que eu possa ter **categorias específicas do meu contexto**.

***

### Critérios de Aceitação:
- No momento de submissão da nota deverá haver a possibilidade de criar uma nova categoria
- Quando uma nova categoria for criada deverá aparecer no dropdown de categorias que poderão ser escolhidas para uma nota
- Uma nova categoria deverá possuir um nome diferente das categorias já existentes
- Uma nova categoria deverá ter uma nova cor associada

**Essa história não contempla:**
- Filtrar notas por categoria
- Gerar relatórios por categoria 

***   

#### _Back-end:_   
- [x] Adicionar categoria ao banco
- [x] Verificar se uma categoria já existe no banco
- [x] Associar nova categoria à uma cor 
- [x] Testes

#### _Front-end_:   
- [x] Criar tela de criação de categoria
- [x] Adicionar nova categoria ao dropdown
- [x] Feedbacks ao usuário
- [x] Responsividade
- [x] Testes

**Comment by MarianaPicolo** [comment]
@clarissalimab e @Phe0 critérios de aceitação;

@Phe0 e @devsalula _tasks_

**Comment by Phe0** [comment]
@clarissalimab valida os critérios de aceitação pra mim por favor

**Comment by clarissalimab** [comment]
Estão ótimos! Muito bem (:
