### ISSUE TITLE
US38 - Editar Nota

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#203]
## US38     

Eu, como **usuário do sistema**, desejo **editar os dados das notas** para que eu possa **corrigí-las**.
***

### Critérios de Aceitação:
- A partir da lista de notas fiscais, o usuário pode selecionar uma nota específica para ter sua visão detalhada.
- Na visão detalhada da nota, o usuário tem a opção de editar os dados da nota.
- O sistema precisa fornecer feedbacks sobre esta ação. Assim, ao salvar, o sistema precisa exibir uma confirmação pedindo que o usuário confira as alterações.

***   

#### _Back-end_:   
- [x] Criar metodo PUT 
- [x] Gateway 
- [x] testes

#### _Front-end_:   
- [x] Colocar os campos da nota como input
- [x] Tornar os campos editáveis pela ação de click
- [x] Botão de confirmar 
- [x] Fazer dialog 
- [x] Axios 
- [x] testes

**Comment by MarianaPicolo** [comment]
@clarissalimab descriçao e critérios de aceitação

@EsioFreitas e @lucasdutraf tasks

**Comment by clarissalimab** [comment]
Coloquei a descrição e os critérios! 😸

**Comment by EsioFreitas** [comment]
@lucasdutraf e eu adicionamos as tasks
