### ISSUE TITLE
US22 - Gerar Relatório por Categoria

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#204]
## US22     

Eu, como **usuário do sistema**, desejo **gerar um relatório de notas fiscais filtrado por categorias**.

***

### Critérios de Aceitação:
- No momento em que um usuário vai gerar um relatório de gastos, ele deverá ter, além da opção de gerar relatórios por data, a opção de gerar relatórios filtrados por categorias.
- O usuário poderá selecionar uma categoria para que os gastos presentes no relatório a ser gerado sigam este critério.
- Ao gerar o relatório, o usuário deverá ter a opção de exportar esse relatório.
- Na geração, o relatório deve mostrar que ele foi gerado a partir da categoria definida.
- Na exportação, o relatório deve mostrar que ele foi gerado a partir da categoria definida.
- O título do relatório deve conter a data em que ele foi gerado.

***   

#### _Back-end_:   
- [x]  Adicionar categoria na função de salvar relatório
- [x]  Mudar a exportação de relatório para levar em consideração a categoria selecionada

#### _Front-end_:   
- [x]  Adicionar categoria nas funções de filtragem de notas
- [x]  Adicionar um dropdown para selecionar a categoria desejada
- [x]  Mudar botões da página de reports para mostrar a categoria

**Comment by MarianaPicolo** [comment]
@clarissalimab critérios de aceitação

@EsioFreitas e @youssef-md _tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios 😸 Não sei se ficaram claros, qualquer coisa me perguntem!
