### ISSUE TITLE
US36 - Associar Notas à Empresa

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#205]
## US36     

Eu, como **administrador de empresa**, desejo que as **notas que eu submeti sejam associadas a minha empresa** para que eu **tenha acesso** somente às **minhas notas**.

***

### Critérios de Aceitação:
- No momento em que uma nota é submetida, ela deve estar associada a empresa que está a submetendo.
- Uma empresa só poderá ver os gastos que estiverem atribuídos a si mesma.

***   

#### _Back-end_:   
- [x]  Listar todos nota
- [x] Listar todas as notas, com filtro de data
- [x] Listar uma nota
- [x] Deletar nota
- [x] Editar tag
- [x]  Listar todos relatórios
- [x]  Refatorar teste Listar todos nota
- [x] Refatorar teste listar todas as notas, com filtro de data
- [x] Refatorar teste Listar uma nota
- [x] Refatorar teste Deletar nota
- [x] Refatorar teste Editar tag
- [x]  Refatorar teste Listar todos relatórios
- [x] Listar todas as notas gateway
- [x] Criar notas gateway
- [x] Deletar notas gateway

#### _Front-end_:   
- [x]  Refatorar requests que passam o company_id hardcoded
- [x] Adicionar company_id ao criar tags

**Comment by MarianaPicolo** [comment]
@clarissalimab critérios de aceitação

@Hargre e @lucasdutraf _tasks_

**Comment by clarissalimab** [comment]
Coloquei os critérios 😺

**Comment by lucasdutraf** [comment]
Além das notas, @Hargre e eu aproveitamos e restringimos o acesso as [tags e aos relatórios](https://github.com/Kalkuli/2018.2-Kalkuli_Gateway/tree/205_Associar_Notas_Empresa)!
