### ISSUE TITLE
US27 - Gerar Gráfico de Gastos Totais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#206]
## US27     

Eu, como **usuário do sistema**, desejo que **gráficos sejam gerados a partir dos gastos totais** para que eu possa ter maior **controle financeiro**.

***

### Critérios de Aceitação:
- Na dashboard, deve ser exibido um gráfico de gastos onde o eixo x deve corresponder ao tempo e o eixo y corresponde ao valor.
- O menor valor do eixo x deve corresponder a data da nota mais antiga inserida, e o maior valor deve corresponder a data da nota mais recente inserida.
- O menor valor do eixo y deve ser R$ 0,00 e o maior valor deve corresponder ao dia com maior gasto + 10% (esses 10% servem para facilitar a visualização).
- Toda vez que uma nova nota for submetida, editada ou excluída, o gráfico deve ser atualizado.

***   

#### _Front-end_:   
- [x]  Determinar a biblioteca de exibição dos Gráficos
- [x] Exibir os gastos pelo tempo 
- [x] Exibir o gráfico de forma dinâmica
- [x] Filtrar notas para mostrar no gráfico
- [x] Ordenar notas 
- [x] Somar valor de notas com datas repetidas
- [x] Responsividade
- [x] Testes

**Comment by MarianaPicolo** [comment]
@clarissalimab critérios de aceitação

@Phe0 e @devsalula _tasks_

**Comment by devsalula** [comment]
@Phe0 encontrou uma biblioteca bem bonita também:
https://apexcharts.com/

**Comment by clarissalimab** [comment]
Coloquei os critérios! Eu não defini o tipo de gráfico porque acho que isso é negociável dependendo do que vocês acharem de ferramenta para gerar, mas pelo que pesquisei aqui na internet, o mais comum é se usar gráfico de barras para este tipo de coisa. Pensei também que não faz tanto sentido gerar um gráfico que tenha todos os gastos da vida da empresa porque se ela tiver muitos gastos, há muito tempo, principalmente, o gráfico não vai fazer sentido, então de qualquer forma essa história vai ser evoluída. Se vocês acharem fácil, vocês podem colocar gastos só do último ano, por exemplo, se não, a gente pode manter só o gráfico de tudo e depois ajustamos.

**Comment by clarissalimab** [comment]
Outra coisa é que se forem fazer gráficos de barras, temos que pensar em qual vai ser o intervalo de cada barra, por exemplo: cada barra é um dia, uma semana, um mês... O ideal era que o usuário pudesse mexer nessa visualização, mas claro que isso não vai acontecer agora haha 😜
