### ISSUE TITLE
Ajustar Responsividade da Aplicação

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#221]
### _Tasks_:    
- [x] ReceiptViewMobile
- [x] Ajustes na Dashboard
- [x] Ajustes na ReceiptView
- [x] Opção de colocar os dados na mão(preview some, e só fica o receiptCompare no Modal)
- [x] Checagem na responsividade geral

**Comment by MarianaPicolo** [comment]
@youssef-md e @EsioFreitas _tasks_

**Comment by youssef-md** [comment]
Tasks iniciais adicionadas
