### ISSUE TITLE
Processo de cadastro com validação incorreta 

### ISSUE THREAD

**Issue by guiaugusto** [fga-eps-mds/2018.2-Kalkuli#235]
# :bug: Bug Report

Não trata corretamente o campo de senha e de confirmar senha [TESTADO NO AMBIENTE DE HOMOLOGAÇÃO].

# To Reproduce

![hotfixissue](https://user-images.githubusercontent.com/26308278/49017322-bda26300-f16f-11e8-9ca0-1f036c8bdd5b.gif)

Quando você coloca as senhas corretamente e depois troca, **sem** trocar o campo de confirmação de senha, ele permite que o usuário crie uma empresa ainda assim. 
Como pode ser visto no _gif_ anterior, a senha é diferente da parte da confirmação, e ainda assim passa pela validação de cores (o campo inválido, que deveria ser de confirmação da senha, não muda de cor para vermelho), consequentemente validando o cadastro.

# Expected Behavior

![expected_solution](https://user-images.githubusercontent.com/26308278/49018308-36a2ba00-f172-11e8-8057-daa339f87fea.gif)

Talvez um comportamento semelhante ao do sistema de registro no [Spotify](https://www.spotify.com/br/signup/) seja uma boa solução, por que manteria a validação pelo Front-end e trabalharia melhor... Pelo o que entendi, ele valida as informações toda vez que eu clico em um campo novo ou em um botão, antes de confirmar as informações.

@RochaCarla

**Comment by lucasdutraf** [comment]
Muito obrigado pelo feedback @guiaugusto ! Buscaremos consertar esse bug o mais rápido possível.

**Comment by Phe0** [comment]
@guiaugusto muito obrigado pelo feedback,
o bug já foi solucionado e um pull request hotfix já foi efetuado.

https://github.com/Kalkuli/2018.2-Kalkuli_Front-End/pull/52

**Comment by guiaugusto** [comment]
Mandaram bem gente xD!
Inclusive, parabéns... O site tá absurdamente sensacional! (falando pela terceira vez kkkk)
