### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-Kalkuli#41]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# Kalkuli

- ## *Issues*

#### **Comunicação**

Vocês estão se comunicando bem nas *issues*, isso é muito bom!

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Conversei com a @clarissalimab e ela me explicou que vocês estavam com dúvidas no processo de pontuação. Alguns links que podem ser úteis pra vocês:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com bons nomes. É interessante a prática de padronizar os nomes, e vocês já fazem utilizando os verbos no infinitivo (que já seria a minha recomendação). Está tudo bem claro e simples como deve ser.

#### ***Labels***

As Labels também estão boas no geral. Provavelmente eu faça um mini-guia para ajudar outros grupos que estão mal nisso, mas definitivamente não é o caso de vocês. A suas são simples e cumprem seu papel.

No geral, as Issues de vocês estão boas, parabéns! (◕‿◕✿)

- ## Documentação

#### **Documento de Visão**

O Documento de Visão de vocês me agradou bastante. É claro que ainda existem coisas a serem adicionadas, mas num primeiro momento, ele está cumprindo a função de:

- Apresentar o problema que vocês querem resolver
- Apresentar os desdobramentos desse problema
- Apresentar qual a solução proposta pelo projeto

Está tudo bem documentado e referenciando, está bem interessante.

#### **Documento de Arquitetura**

O Documento de Arquitetura ainda não está pronto, mas assim que estiver eu atualizo esse feedback.

#### **Documentação Geral**

O que já tem de documentação até aqui é bem interessante. A forma como vocês estão utilizando para mostrar as sprints e os resultados delas está sendo uma boa forma de transparecer os progressos que vocês estão tendo. É interessante o uso do quadro de conhecimento, e do quadro de presença nas *daily's*.
Minha recomendação é que se for possível, tentem fazer as *daily's* por hangouts. Isso melhora a comunicação da equipe, e também contribui para uma maior colaboração e união do time.

- ## Considerações Finais

O trabalho de vocês parece estar bem encaminhado, vocês são um dos melhores grupos em questão de evolução, parabéns!  ( ⌒o⌒)人(⌒-⌒ )

Uma sugestão é, atualizem o README de vocês assim que puderem, com uma explicação básica do projeto, ou o link para o Documento de Visão, fiquei meio perdido quando entrei pela primeira vez.

A Carla vai poder dar um feedback melhor em coisas específicas, mas espero ter contribuído na melhoria do andamento do projeto de vocês.

[]s, @fepas

**Comment by MarianaPicolo** [comment]
@fepas Muito obrigada pelo feedback!

Adotarei as sugestões!
:DD
