### ISSUE TITLE
Pesquisar sobre visualização de dados

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#42]
#  Pesquisar sobre visualização de dados    

Reunir material sobre exibição de dados em gráficos.

**Comment by devsalula** [comment]
Segue alguns links, sobre DataViz:
https://www.columnfivemedia.com/data-visualization-101-area-charts
https://www.columnfivemedia.com/data-visualization-101-line-charts
https://www.columnfivemedia.com/data-visualization-101-bar-charts
https://www.columnfivemedia.com/data-visualization-101-pie-charts
Esse está "desatualizado", porém é um ótimo texto:
https://blog.dp6.com.br/como-escolher-o-melhor-gráfico-para-meus-dados-dataviz-basics-2-de-4-9360ff6c8f8a

**Comment by Phe0** [comment]
Biblioteca para criação de gráficos: 
https://www.chartjs.org/
