### ISSUE TITLE
Refatorar Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#50]
Refatorar protótipo de alta fidelidade para que se adeque à [identidade](https://github.com/fga-eps-mds/2018.2-Kalkuli/issues/22) visual.

- [ ] Atualizar a _wiki_
   - [ ] Identidade visual
   - [ ] Protótipo

**Comment by Phe0** [comment]
Protótipo de alta fidelidade da seção de adicionar notas :
https://xd.adobe.com/view/db64571f-82f7-4449-53f2-e2c0db4b3bdb-ad55/
