### ISSUE TITLE
US13 - Listar Notas Fiscais

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#72]
## US13     

Eu, como **usuário do sistema**, desejo **visualizar uma lista de todas as notas fiscais** submetidas para **ter acesso a todas as notas**.  

***

### Critérios de Aceitação:   
* O sistema deve exibir uma tela com uma lista de todas as notas fiscais submetidas;
* A tela deve seguir a identidade visual do projeto;
* No conteúdo de cada item da lista deve existir o nome da nota, a data e o valor total.

***   

#### Back-end
- [x] Solicitar do banco de dados as notas salvas 
- [x] Retornar JSON com todas as notas
#### Front-end
- [x] Apresentar as notas solicitadas

**Comment by MarianaPicolo** [comment]
@clarissalimab   
- Critérios de aceitação  


@lucasdutraf e @EsioFreitas   
- Tasks

**Comment by clarissalimab** [comment]
Coloquei os critérios! 😋

**Comment by lucasdutraf** [comment]
@EsioFreitas e eu colocamos as tasks!

**Comment by lucasdutraf** [comment]
Sobre requisições usando react:
https://alligator.io/react/axios-react/
https://reactjs.org/docs/faq-ajax.html
