### ISSUE TITLE
Criar Roadmap do Produto

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#8]

**Comment by Hargre** [comment]
A gente podia atualizar essa issue pra conter os roadmaps de cada papel

**Comment by MarianaPicolo** [comment]
Eu coloquei esse pensando no roadmap do produto mesmo

**Comment by MarianaPicolo** [comment]
Para os papéis, é melhor abrir uma nova issue de roadmap mesmo
