### ISSUE TITLE
US14 - Visualizar Uma Nota Detalhadamente

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#92]
## US14     

Eu, como **usuário do sistema**, desejo **visualizar uma nota detalhadamente** para que eu possa **verificar os dados**.

***

### Critérios de Aceitação:   
- A nota em detalhes deve ser vista a partir de uma nota selecionada na lista.
- A visão detalhada da nota deve ter todas as informações extraídas da nota e deve estar preparada para receber a visualização em PDF da nota correspondente (ainda não é necessário que o PDF exibido seja o da nota porque o sistema ainda não armazena os PDFs).
- A tela deve seguir o manual de identidade visual do projeto.

***   

#### Front-end:
- [x] Conseguir acessar a nota
   - [x] Tornar as notas já existentes clicáveis
   - [x] Abrir a área referente a nota singular
- [x] Implementar a área de visualização da nota 
   - [x] Estilizar os dados da nota
   - [x] Adicionar botão de download
   - [x] Posicionar os botões
 - [x] Corrigir o BackDrop
#### Back-end: 
- [x] Criar método que faça requisição de uma única nota
- [x] Realizar testes com o método criado

**Comment by MarianaPicolo** [comment]
@clarissalimab:
 - Critérios de aceitação

@youssef-md, @lucasdutraf e @EsioFreitas 
- Tasks

**Comment by youssef-md** [comment]
A biblioteca que provavelmente vamos usar é a pdfJS: https://mozilla.github.io/pdf.js/ pois tem esse exemplo  em ReactJS bem detalhado para a visualização do arquivo: https://github.com/jjperezaguinaga/pdf-viewer

**Comment by clarissalimab** [comment]
Já coloquei os critérios de aceitação! 😺

**Comment by lucasdutraf** [comment]
Tasks criadas!

**Comment by youssef-md** [comment]
Essa história deve ser destinada tanto no envio de uma nova nota, quanto na edição de uma ja existente?

**Comment by MarianaPicolo** [comment]
> Essa história deve ser destinada tanto no envio de uma nova nota, quanto na edição de uma ja existente?

Ele clica em uma nota da lista, e é redirecionado para esta tela:
https://xd.adobe.com/view/db64571f-82f7-4449-53f2-e2c0db4b3bdb-ad55/screen/117426f5-c0a3-4ebf-94a3-c318ec5f0173/-rea-de-Notas

**Comment by lucasdutraf** [comment]
@EsioFreitas @youssef-md e eu dividimos as tasks antes colocadas em menores partes! :+1:

**Comment by EsioFreitas** [comment]
Essa lib foi usada para abrir as notas 
<https://react-popup.netlify.com/home/>
