### ISSUE TITLE
Refatorar Documento de Visão

### ISSUE THREAD

**Issue by MarianaPicolo** [fga-eps-mds/2018.2-Kalkuli#95]
## Refatorar Documento de Visão

- [x] Atualizar _wiki_

**Comment by MarianaPicolo** [comment]
Meninos, não sei se perceberam, mas os títulos que estão marcados com apenas uma '#', não estão sendo exibidos.

Adicionem mais um '#' em cada tópico de título, que eles voltam ao normal.

Onde tem dois, coloquem três, e assim sucessivamente, assim as hierarquias continuam preservadas.

**Comment by clarissalimab** [comment]
Coloquem o Espresso como concorrente também https://www.espressoapp.com.br/
